### ISSUE TITLE
Awaiting within an arrow function

### ISSUE THREAD

**Issue by jakearchibald** [tc39/ecmascript-asyncawait#7]
Assuming `getJSON` returns a promise for some JSON, does this work:

``` js
async function renderChapters(urls) {
  urls.map(getJSON).forEach(j => addToPage((await j).html));
}
```

Does the await within the arrow function halt the execution of both the `forEach` and `renderChapters`, or does it error because the arrow function is not an async function?

If not, should we have a way to await to the parent async function?

**Comment by Ajedi32** [comment]
So just to clarify, the original example (which doesn't work):

``` javascript
async function renderChapters(urls) {
  urls.map(getJSON).forEach(j => addToPage((await j).html));
}
```

Could actually be written in one of three ways, with slightly differing results. If you write it like this:

``` javascript
async function renderChapters(urls) {
  for (let j of urls.map(getJSON)) {
    addToPage((await j).html);
  }
}
```

Which is the closest to what was originally written, then all `getJSON` operations will happen in parallel, with the results being added to the page sequentially as they come in. The result of later requests will not be added to the page before the result of previous requests. (E.g. The result of the second request will not be added to the page before the first one.)

If you write it like this:

``` javascript
async function renderChapters(urls) {
  (await Promise.all(urls.map(getJSON))).forEach(j => addToPage(j.html));
}
```

Then all getJSON operations will happen in parallel, and the application will wait until all requests are complete before adding them all to the page at once.

Or if you write it like this:

``` javascript
async function renderChapters(urls) {
  await Promise.all(urls.map(getJSON).map(async j => addToPage((await j).html)));
}
```

Then all getJSON operations will happen in parallel, and each object will be added to the page as it arrives (possibly out of order).

Example here: http://www.es6fiddle.net/iftvukev/ (Or [on Babel](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=function%20delayedPromise%28time%2C%20value%29%20%7B%0D%0A%20%20return%20new%20Promise%28function%28resolve%2C%20reject%29%20%7B%0D%0A%20%20%20%20setTimeout%28%28%29%20%3D%3E%20resolve%28value%29%2C%20time%29%0D%0A%20%20%7D%29%0D%0A%7D%0D%0A%0D%0Aasync%20function%20serial%28%29%20%7B%0D%0A%20for%20%28let%20i%20%3D%200%3B%20i%3C10%3B%20i%2B%3D1%29%20%7B%0D%0A%20%20let%20promise%20%3D%20delayedPromise%28Math.random%28%29%20*%201000%2C%20i%29%0D%0A%20%20let%20result%20%3D%20await%20promise%0D%0A%20%20console.log%28%22Resolved%20serial%3A%20%22%20%2B%20result%29%0D%0A%20%7D%0D%0A%20console.log%28%22Done%20with%20serial!%22%29%0D%0A%7D%0D%0A%0D%0Aasync%20function%20parallel%28%29%20%7B%0D%0A%20%20let%20promises%20%3D%20range%280%2C%2010%29.map%28%28i%29%20%3D%3E%20delayedPromise%28Math.random%28%29%20*%201000%2C%20i%29%29%0D%0A%20%20for%20%28let%20promise%20of%20promises%29%20%7B%0D%0A%20%20%20%20console.log%28%22Resolved%20parallel%3A%20%22%20%2B%20await%20promise%29%0D%0A%20%20%7D%0D%0A%20%20console.log%28%22Done%20with%20parallel!%22%29%0D%0A%7D%0D%0A%0D%0Aasync%20function%20all%28%29%20%7B%0D%0A%20%20let%20promises%20%3D%20range%280%2C%2010%29.map%28%28i%29%20%3D%3E%20delayedPromise%28Math.random%28%29%20*%201000%2C%20i%29%29%0D%0A%20%20await%20Promise.all%28promises.map%28async%20%28promise%29%20%3D%3E%20console.log%28%22Resolved%20all%3A%20%22%20%2B%20await%20promise%29%29%29%0D%0A%0D%0A%20%20console.log%28%22Done%20with%20all!%22%29%0D%0A%7D%0D%0A%0D%0Aasync%20function%20race%28%29%20%7B%0D%0A%20%20let%20promises%20%3D%20range%280%2C%2010%29.map%28%28i%29%20%3D%3E%20delayedPromise%28Math.random%28%29%20*%201000%2C%20i%29%29%0D%0A%20%20console.log%28%22Resolved%20race%3A%20%22%20%2B%20await%20Promise.race%28promises%29%29%0D%0A%0D%0A%20%20console.log%28%22Done%20with%20race!%22%29%0D%0A%7D%0D%0A%0D%0Afunction%20range%28start%2C%20count%29%20%7B%0D%0A%20%20return%20Array.apply%280%2C%20Array%28count%29%29%0D%0A%20%20%20%20.map%28function%20%28element%2C%20index%29%20%7B%20%0D%0A%20%20%20%20%20%20return%20index%20%2B%20start%3B%20%20%0D%0A%20%20%20%20%7D%29%3B%0D%0A%7D%0D%0A%0D%0Aserial%28%29.then%28parallel%29.then%28all%29.then%28race%29).)

Edit: Replaced `await*` with `await Promise.all(...)`

Edit 2: Added Babel mirror of example, clarify that original example is broken.

**Comment by domenic** [comment]
await\* is nonstandard syntax

**Comment by Ajedi32** [comment]
It is? Eh, well you can always just replace it with `await Promise.all(...)` since that's really all it's doing anyway. `await*` did work fine for me in Babel though.

**Comment by domenic** [comment]
Yes, Babel is not standards compliant.

**Comment by sebmck** [comment]
Actually @domenic, Babel is spec complaint. The addition of something non standard doesn't make it not compliant, not unless it's explicitly forbidden. That doesn't matter anyway since it's already been removed for Babel 6 (babel/babel#2466)

**Comment by bterlson** [comment]
To be pedantic, no implementation is completely standards compliant. @domenic's statement is not wrong but not saying much either :-P

**Comment by barneycarroll** [comment]
Sorry for reviving this thread all these months later. This thread is cited in multiple places as an explanation of why async arrow functions are impossible, but I'm not getting that. AFAICT, the point @domenic is making is that you are unleashing event loop Zalgo if you expect a synchronous operation to be able to invoke code which `await`s internally. That's fair enough, the `forEach` example is legit, and it's a fundamental issue to grok when you want to do `await`: one can only `await` directly inside an `async` scope. 

To be clear: `forEach` synchronously executes the iterator function for each item in the array. We can't expect the parser to go "oh but obs we want some kind of async `forEach`" based on the contents of the iterator, because A) that's way too much assumptive black magic and B) it's ambiguous: should the iteration happen sequentially or parallel? @Ajedi32 [shows us how to get around that with solid, explicit code that doesn't just hand wave fundamental concerns of asynchrony](https://github.com/tc39/ecmascript-asyncawait/issues/7#issuecomment-148748622)

So that's solved. What I don't get is how arrows relate to any of this. AFAICT the only concern there is that we have lexical this, but isn't that just as problematic as exposing any higher scope state? And even if it's a special kind of dangerous and horrible, isn't that _just_ bad practice or 'considered dangerous' as opposed to logically impossible or semantically ambiguous?

**Comment by getify** [comment]
> async arrow functions are impossible

They're not. `(async x => await x)(y)` would be just fine, IIUC.

> What I don't get is how arrows relate to any of this.

IMO, they don't. I was incorrect earlier in the thread, for sure, but what I now realize is that @domenic's first comment was totally correct... Any kind of function, normal or arrow or otherwise, couldn't call `await` from inside it and have that affect its outer `async function`. That'd be a deep continuation, and it's just not going to happen.

If this thread is related to arrow functions particularly, it's that it highlights how easy it is to mistake an arrow function (conceptually) for just a block, in which you _would_ expect to still be able to easily `await`. I suspect if the OP had used a normal inner function, arrow's might never have been brought into it.

**Comment by Marak** [comment]
This conversation is mildly terrifying to me.

Let's try not assume we are all are correct and end up in another `peerDependencies` situation like we had with `npm`.

Try to stay open-minded. Cheers.

**Comment by bgrayburn** [comment]
I realize this convo is a beast, but wanted to throw out a decorator to accomplish this (sort of)

```async asyncAwaitDecorator(f, f_args, f_prime=a=>a){
    return f_prime(await f(...f_args))
}```

untested, so if you do try let me know any errors
this seems like it solves a large swatch of use-cases, and shouldn't care if f and f_prime are anonymous.

my first thought after writing the above function: "man I wish I could make that whole thing an arrow function" can't win

**Comment by caub** [comment]
```js
(async () => {

  [7, 8].forEach(async i => {
	const html = await fetch('https://github.com/tc39/ecmascript-asyncawait/issues/').then(x=>x.text());
	console.log(i, html.slice(0, 200));
  });

})()

```
